### ISSUE TITLE
code highlight support ??

### ISSUE THREAD

**Issue by eggcaker** [bdewey/org-ruby#19]
any plan to support  code highlight ?? right now , only convert `#+begin_src ruby`  to pre with `class="src"`

**Comment by wallyqs** [comment]
Maybe this could be possible by using something like Pygments like [jekyll](https://github.com/mojombo/jekyll/issues/90) does, though this would introduce a dependency of Python. I will look into working something out in a branch.

**Comment by eggcaker** [comment]
yes , I'm came from [Jekyll](http://jekyllrb.com)

 by default , org-ruby ignored the lang define in org-mode file like my comment before, but maybe it's better if org-ruby can process the `#+begin_src ruby` to `<pre class="ruby">`  instead of `<pre class="src">` woud be better then the Jekyll can precess them to hightlighted

**Comment by wallyqs** [comment]
I added this to my branch, now it inserts of code tags to #BEGIN_SRC code blocks in a similar fashion that Jekyll does with its {highlight} tag. So at least now Javascript based syntax-highlighting solutions should be easy to implement.

https://github.com/eggcaker/org-ruby/commit/1b9e838af84ce3cf0558ad2e2348a94d1aa976c3

I think I will I give it a try to CodeRay to support code syntax highlighting out of the box, since CodeRay is also pure ruby like org-ruby.

**Comment by eggcaker** [comment]
good work! wallyqs

**Comment by wallyqs** [comment]
I added code syntax highlighting with CodeRay here: 
https://github.com/wallyqs/org-ruby/commit/c4c4817a97f4387df505683060d11ac91308c0c3 

Hope this helps!
