### ISSUE TITLE
Add support for syntax highlighting

### ISSUE THREAD

**Issue by punchagan** [bdewey/org-ruby#26]
Using [albino](https://github.com/github/albino/) or [pygments.rb](https://github.com/tmm1/pygments.rb) add support for syntax highlighting.   The fact that the html output is flushed one line at a time, makes it a little tricky (for me, with my rudimentary ruby skills) to do this.

**Comment by wallyqs** [comment]
I did some work for this on my branch, but using coderay instead. Ideally, it should be possible to opt for using coderay (pure ruby) or albino(github support, gollum). 

https://github.com/wallyqs/org-ruby/commit/1b9e838af84ce3cf0558ad2e2348a94d1aa976c3
https://github.com/wallyqs/org-ruby/commit/c4c4817a97f4387df505683060d11ac91308c0c3

**Comment by punchagan** [comment]
That's cool!  I suggested `albino` since GitHub seems to use that and that would give proper syntax highlighting on GitHub.

**Comment by wallyqs** [comment]
I included support to syntax highlight code blocks with Pygments.rb (since albino is deprecated) in the `code-syntax-highlight` branch. This is not complete though, I still have to polish and adapt it so that it works nicely with Gollum and other technologies.
https://github.com/bdewey/org-ruby/commit/8dc7348834efa04a2b3e5963b66755828421d1c7

**Comment by wallyqs** [comment]
Ok! Starting from version 0.7.0 gem code blocks should be highlighted when either Pygments.rb or CodeRay are available. Also works when using it with Jekyll or Gollum.

**Comment by punchagan** [comment]
Awesome!  Cheers!
