### ISSUE TITLE
checkbox parsing problem.

### ISSUE THREAD

**Issue by huseyinyilmaz** [bdewey/org-ruby#63]
Hello,
I believe this is the library that is used by github. I am using gists to render org-mode files and I realized that certain structures stops checkbox lists from being rendered.
I created a sample document to show the problematic structure. Line that marked with XXX is the one that stop checkboxs from rendering.

https://gist.github.com/huseyinyilmaz/b29c2311fcc92e827f97

**Comment by wallyqs** [comment]
Hi, thank you for sharing.  This is a bit complicated: currently the Org Ruby gem has not implemented tasks lists rendering as input checkboxes, so I think this functionality may be due to some thing that Github is doing to the markup: https://github.com/blog/1841-nested-task-lists
Also the version being used in Gist might be different, since it does not have syntax highlighting either...
I will be improving the parser and rendering output soon so that it is more reliable. By the way further development of the gem is done here: https://github.com/wallyqs/org-ruby

**Comment by huseyinyilmaz** [comment]
I see, 
So this particular structure, somehow masses up github's task list rendering. 
Thanks for looking into it.
